server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-center-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ky2009888/spring-cloud-config-demo02.git
          search-paths:
            - spring-cloud-config-demo02
          password: ########
          username: ########
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: ########
    password: ########
#eueka客户端的配置
eureka:
  client:
    #表示当前项目要注册到eureka server上面
    fetch-registry: true
    #是否抓取已注册的信息，true表示抓取
    fetchRegistry: true
    #eureka server的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80
    #ip地址显示
    prefer-ip-address: true
#暴露监控的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
