server:
  port: 80
spring:
  application:
    name: cloud-consumer-order80-openfeign-hystrix
#eueka客户端的配置
eureka:
  client:
    #表示当前项目要注册到eureka server上面
    fetch-registry: true
    #是否抓取已注册的信息，true表示抓取
    fetchRegistry: true
    #eureka server的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80
    #ip地址显示
    prefer-ip-address: true
#设置openfeign的超时时间
feign:
  client:
    config:
      remote-service:
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    org.jliang.apps.cloud.service.PaymentFeignService: debug