#项目基础配置
server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  #数据源的配置
  datasource:
    username: root
    password: Qwer@#1234
    url: jdbc:mysql://localhost:13306/mydb?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.jliang.apps.cloud.entity
#eueka客户端的配置
eureka:
  client:
    #表示当前项目要注册到eureka server上面
    fetch-registry: true
    #是否抓取已注册的信息，true表示抓取
    fetchRegistry: true
    #eureka server的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    #ip地址显示
    prefer-ip-address: true
