server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示eureka本身向自己注册自己
    register-with-eureka: false
    service-url:
      #设置EUREKA服务器的地址，用于客户端和EUREKA服务器端进行服务的注册和检索
      defaultZone: http://eureka7002.com:7002/eureka/
    #表示自己就是注册中心，进行实例维护，不需要检索服务
    fetch-registry: false
    #false代表关闭自我保护机制
    #server:
    #enable-self-preservation: false