server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-nacos-80
  #nacos客户端的配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
service-url:
  nacos-user-service: http://spring-cloud-payment-nacos-provider